apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcp-simulator.fullname" . }}
  labels:
    {{- include "gcp-simulator.labels" . | nindent 4 }}
type: Opaque
stringData:
  GCP_SIM_DATABASE_URL: {{ include "gcp-simulator.databaseUrl" . | quote }}
  GCP_SIM_DEV_TOKEN: {{ .Values.simulator.devToken | quote }}
